force-app/main/default/objects/Hiring_Company__c/Hiring_Company__c.object-meta.xml
<CustomObject>
    <description>The hiring company is the company which posted the job ad. It could be the actual employer or a recruiting agency.</description>
    <label>Hiring Company</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Hiring Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiring Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Company__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>Name of the company</description>
    <inlineHelpText>Enter the legal name of the hiring company. If the ad has been placed by a recruiting agency, then enter the name of the recruiting agency.</inlineHelpText>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Central object representing a user’s job application</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JOB-{0000000000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Job responsibilities, qualifications, etc.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Id of Job Application on external system</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Hiring_Company__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Company</label>
    <referenceTo>Hiring_Company__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>City, region, or &quot;Remote&quot;</description>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>Job title being applied for.</description>
    <label>Position/Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Offered or expected salary</description>
    <label>Salary</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Name of job board or &quot;manual&quot; for manual entry</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Job type (full-time, part-time, etc.).</description>
    <inlineHelpText>Enter the job type (full-time, part-time, etc)</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Link to the job posting</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/tests/FindNewJobsControllerTest.cls
@isTest
private without sharing class FindNewJobsControllerTest {
    @isTest
    static void findJobsJoobleSuccessTest(){
        String keywords = 'Salesforce';
        String location = 'Montreal';
        String salary = '10';
        String apiName = 'Jooble';

        Test.setMock(HttpCalloutMock.class, new ZombiesHttpCalloutMockImpl());

        test.StartTest();

        String searchId = FindNewJobsController.findJobs(keywords, location, salary, apiName);

        test.StopTest();

        Assert.areNotEqual(null, searchId, 'The searchId should not be null');
    }

    @isTest
    static void saveJobsJoobleSuccessTest(){
        Hiring_Company__c testCompany = new Hiring_Company__c( Company_Name__c = 'Test Company');
        List<Map<String, Object>> jobsList = new List<Map<String, Object>>();
        Map<String, Object> jobsMap = new Map<String, Object>();
        jobsMap.put('Position_Title__c', 'Test Job');
        jobsMap.put('Hiring_Company__c', testCompany.Id);
        jobsMap.put('Location__c', 'Test city');
        jobsMap.put('Description__c', 'This is a description of the job post');
        jobsMap.put('Source__c','Jooble');
        jobsMap.put('Salary__c','195k');
        jobsMap.put('Type__c','Part-time');
        jobsMap.put('URL__c','https://fakeurl.com');
        jobsMap.put('External_Id__c','-12345678');
        jobsMap.put('Company_Name__c','Test Company Name');
        jobsList.add(jobsMap);

        Test.startTest();

        String result = FindNewJobsController.saveJobs(jobsList);

        Test.stopTest();

        List<Job_Application__c> insertedJobs = [SELECT Id, Position_Title__c, Hiring_Company__c, Location__c, Description__c, Source__c, Salary__c, Type__c, URL__c, External_Id__c, Company_Name__c FROM Job_Application__c WHERE External_Id__c = '-12345678'];

        Assert.areEqual(1, insertedJobs.size(), 'There should be one inserted job application record');
        Assert.areEqual('Test Company Name', insertedJobs[0].Company_Name__c, 'Company Name does not match expected value');

    }

}