force-app/main/default/objects/Hiring_Company__c/Hiring_Company__c.object-meta.xml
<CustomObject>
    <description>The hiring company is the company which posted the job ad. It could be the actual employer or a recruiting agency.</description>
    <label>Hiring Company</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Hiring Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiring Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Company__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>Name of the company</description>
    <inlineHelpText>Enter the legal name of the hiring company. If the ad has been placed by a recruiting agency, then enter the name of the recruiting agency.</inlineHelpText>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Central object representing a user’s job application</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JOB-{0000000000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Job responsibilities, qualifications, etc.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Id of Job Application on external system</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Hiring_Company__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Company</label>
    <referenceTo>Hiring_Company__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>City, region, or &quot;Remote&quot;</description>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>Job title being applied for.</description>
    <label>Position/Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Offered or expected salary</description>
    <label>Salary</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Name of job board or &quot;manual&quot; for manual entry</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Job type (full-time, part-time, etc.).</description>
    <inlineHelpText>Enter the job type (full-time, part-time, etc)</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Link to the job posting</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/strategies/parsing/JoobleWrapperParsingStrategy.cls
public with sharing class JoobleWrapperParsingStrategy implements IWrapperParsingStrategy{
    public Map<String, List<Object>> parse(Object wrapper) {

        Map<String, List<Object>> records = new Map<String, List<Object>>();

        List<Job_Application__c> jobApplications = new List<Job_Application__c>();
        List<Hiring_Company__c> hiringCompanies = new List<Hiring_Company__c>();


        
        Map<String, Id> hiringCompanyNameIdMap = new Map<String, Id>();
        Map<String, String> externalIdCompanyNameMap = new Map<String, String>();
    
        Set<String> allCompanyNames = new Set<String>();
        Set<String> companyNamesInDatabase = new Set<String>();
        for(JoobleResponseWrapper.Job job : ((JoobleResponseWrapper)wrapper).jobs){
            if (String.isNotBlank(job.company)) {
                allCompanyNames.add(job.company.trim());
            }
        }

        for(Hiring_Company__c company : [SELECT Id, Company_Name__c FROM Hiring_Company__c WHERE Company_Name__c IN :allCompanyNames]){
            hiringCompanyNameIdMap.put(company.Company_Name__c, company.Id);
            companyNamesInDatabase.add(company.Company_Name__c);
            hiringCompanies.add(company);
        }

 

        // Clone allCompanyNames so we don't modify the original
        Set<String> companyNamesNotInDatabase = new Set<String>(allCompanyNames);
        companyNamesNotInDatabase.removeAll(companyNamesInDatabase);

        List<Hiring_Company__c> hiringCompaniesToInsert = new List<Hiring_Company__c>();
        for(String companyName : companyNamesNotInDatabase){
            Hiring_Company__c company = new Hiring_Company__c();
            company.Company_Name__c = companyName;
            hiringCompaniesToInsert.add(company);
        }

        insert hiringCompaniesToInsert;
        hiringCompanies.addAll(hiringCompaniesToInsert);

        
        for(Hiring_Company__c company : hiringCompaniesToInsert){
            hiringCompanyNameIdMap.put(company.Company_Name__c, company.Id);
        }

        for(JoobleResponseWrapper.Job job : ((JoobleResponseWrapper)wrapper).jobs){
            
            Job_Application__c jobApplication = new Job_Application__c();           
            jobApplication.Position_Title__c = job.title;
            jobApplication.Hiring_Company__c = hiringCompanyNameIdMap.get(job.company);
            jobApplication.Location__c = job.location;
            jobApplication.Description__c = job.snippet;
            jobApplication.Source__c = job.source;
            jobApplication.Salary__c = job.salary;
            jobApplication.Type__c = job.type;
            jobApplication.URL__c = job.link;
            jobApplication.External_Id__c = job.id;
            jobApplications.add(jobApplication);
        }
        
        
        Database.insert(jobApplications, false);
        
        records.put('Jobs', jobApplications);
        records.put('Companies', hiringCompanies);
        return records;
    }
}