force-app/main/default/objects/Job_API_Configuration__mdt/Job_API_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Stores endpoint metadata and configuration.  Belongs to the data layer.</description>
    <label>Job API Configuration</label>
    <pluralLabel>Job API Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Job_API_Configuration__mdt/fields/Body_Template__c.field-meta.xml
<CustomField>
    <fullName>Body_Template__c</fullName>
    <description>Dynamic Body Template. Must be valid JSON</description>
    <label>Body Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_API_Configuration__mdt/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Optional additional headers. Must be valid JSON.</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_API_Configuration__mdt/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <description>Callout Method</description>
    <label>Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_API_Configuration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable / Disable the configuration</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_API_Configuration__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Reference to the Named Credential</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/strategies/callouts/JobSearchApiCalloutStrategyFactory.cls
public with sharing class JobSearchApiCalloutStrategyFactory {
    public static IJobSearchApiCalloutStrategy getStrategy(String apiName) {
        Job_API_Configuration__mdt config = new Job_API_Configuration__mdt();
        try{
            config = [
            SELECT Named_Credential__c, Http_Method__c, Headers__c, Body_Template__c, Is_Active__c
            FROM Job_API_Configuration__mdt
            WHERE DeveloperName = :apiName
            LIMIT 1
        ];
            }catch(QueryException e){
                System.debug(e.getMessage());          
            }
        return new MetadataDrivenApiStrategy(config);
    }
}